# Generated by Django 5.1.3 on 2024-11-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.branch'),
        ),
    ]
