# Generated by Django 5.1.3 on 2024-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_message_post_alter_post_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
