# Generated by Django 5.1.3 on 2024-11-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_message_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='review',
            new_name='views',
        ),
    ]
